
github:
  clientId : a63bb0776b70be956f87
  clientSecret : b03191ae6d9fc51d8bd870b3b37bb94762beb30f
  token : 11096939fe3f46697e7727dd5df82839e4e18ece

stackoverflow:
  key : WaTAupj4SVFVSUbkqe0jlQ((
  site : stackoverflow

twitter:
  consumerKey : RslTXjTdnEwRLcOXHyaK1oxmA
  consumerSecret : LUYwCQVkZ4bwDncTiTnxRU0Y1LYzgpuxlcM5gVrp3rLgfDQBBJ
  accessToken : 949848603522039808-i4esEowB0UcQy6rgzXyHVhCrEzWegQ7
  secret : GBxIDkIHREOzQEnClIfTbSzTqIV6rnjfP7lJxMGZnjO9c

